### ISSUE TITLE
Design Note

### ISSUE THREAD

**Issue by AnuthinWongsunkakon** [cadsondemak/Sarabun#2]
The latin in the original design required a major change. Especially lowercase g. Obviously the tail loop is too small and too short.

**Comment by davelab6** [comment]
Great to see such discussions, to help inform future designers and
contributors :)

**Comment by suppakit-** [comment]
Thanks for the suggestions. Now i change g form. :D

**Comment by AnuthinWongsunkakon** [comment]
I think some of the characters that you have improved in the TH New version can also be improved. Such as Karan (์) can be a bit longer so it will pronounce better when using it in a small size. Preventing it to look like just circle (Narukahit). The loop and diagonal line inside TorTao (ต) shall have not get too close to the back stem. The spacing for the uppercase Latin is a bit too tight in my opinion. I have not had a chance to look at the lowercase just yet. Improving this will also help when the face get bolder as well. Please consider.

**Comment by suppakit-** [comment]
ขอบคุณครับ ผมจะตรวจทานช่องไฟของตัวพิมพ์ใหญ่ และปรับให้ดียิ่งขึ้นอีกครั้งครับ และเมื่อมีการวาดใหม่ของตัวอักษรไทย ผมจะสังเกตรายละเอียดต่างๆ ของวรรณยุกต์อย่างใกล้ชิดและปรับให้ดีขึ้น ขอบคุณสำหรับข้อสังเกตและคำชี้แนะครับ :D

**Comment by AnuthinWongsunkakon** [comment]
I have read from somewhere recently about the complaint of lowercase g of Sarabun. Was that on Facebook or something. Shall we do the g tail as an alternate?

**Comment by davelab6** [comment]
GF doesn't support non-essential opentype features today, but it may in the
future, so good to add it. However, I'm happy to see the default glyphs
updated to be their best :)

**Comment by AnuthinWongsunkakon** [comment]
Would it be possible that the italic version of Sarabun will be less extreme old fashion. I mean the heavily handwriting flare at the end of the strokes. Shorter end tale stroke and less curvy.  I personally think it does not fit well with todays‘s context and it obviously get less use in document purpose. Many people shy away from using the italic version of the original because it looks a bit dated.

**Comment by suppakit-** [comment]
เห็นด้วยเช่นกันครับ ตามแผนการณ์ที่คิดไว้ สำหรับรุ่นนี้จะทำตัวเอนแบบปกติครับ ไม่ใส่จริตแบบที่เคยใส่ไว้ในตัวสารบรรณดั้งเดิม
