### ISSUE TITLE
ตัวเอียงภาษาไทย

### ISSUE THREAD

**Issue by AnuthinWongsunkakon** [cadsondemak/Sarabun#3]
ขออนุญาตเปิดประเด็นตัวเอียงเป็นอีกประเด็นนึงตรงนี้ จะได้ไม่ปนกันในประเด็นก่อนหน้านี้ เพราะผมมีพูดถึงตังเอียงไป และคิดว่าจะฝากเป็นรีเควสตรงนี้เรื่องดีกรีการใส่จริตให้กับตัวเอียงของสารบรรณรุ่นใหม่นี้ 

เนื่องจากตัวไทยไม่ค่อยใช้ตัวเอียงมากนัก คือมีใช้งานแต่ก็อาจจะไม่ได้ถูกเลือกบ่อย แต่จำเป็นต้องมี เหตุหนึ่งที่ทำให้ตัวเอียงของสารบรรณไม่ค่อยเป็นที่นิยมอาจเป็นเพราะว่ามีกลิ่นอายของความเป็นการเขียนโบราณมากไปสักนิด ซึ่งต่างกับตัวตั้งตรงที่ดูจะแคร์เรื่องจริตของลายมือน้อยกว่าอย่างเห็นได้ชัด 

นอกจากจะทำให้ไปคนละทิศทางในต่างดีกรีของเจตนาแล้ว จึงน่าจะเป็นเหตุส่วนนึงที่ทำให้โอกาสการใช้ตัวเอียงในงานเอกสารมีความเป็นไปได้น้อยลงด้วย ผมจึงขออนุญาตฝากเรื่องนี้ไว้ รบกวนว่าประเด็นตัวเอียงเราจะสามารถแยกมาถกกันในกระดานนี้แทน

**Comment by suppakit-** [comment]
ผมคิดเห็นตรงกันครับ สำหรับรุ่นนี้ จะทำตัวเอนแบบปกติ โดยไม่เพิ่มเติมจริตพิเศษในลักษณะตัวเขียนแบบในสารบรรณดั้งเดิม หลังจากผ่านการใช้งานมาได้ระยะนึงรู้สึกได้ว่ามันดูไม่เข้ากับบริบทในปัจจุบันสักเท่าไหร่ และยังรู้สึกขัดใจตัวผู้ออกแบบเองด้วยครับ

**Comment by AnuthinWongsunkakon** [comment]
ซึ่งจริงๆแล้วเรื่องตัวเอียงไทย คงต้องคุยกันยาว ผมไม่ได้ติดที่คุณภาพของแบบดั่งเดิมเลยนะ แค่เรื่องของความเข้ากันเท่านั้น ส่วนตัวถ้าเป็นผม ผมจะเก็บตัวเอียงเดิม เพื่อเอาไว้ทำตรงทีหลัง เป็นสปินออฟได้อีกตระกูลนึงครับ
